services:
  backend:
    build: .
    container_name: backend
    command: >
      sh -c
      "python manage.py makemigrations &&
       python manage.py migrate &&
       python manage.py collectstatic --noinput &&
       exec gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - redis
    environment:
      - DEBUG=False
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - redis
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4
  beat:
    build: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./:/app
    depends_on:
      - redis
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  smtp4dev-data:

