name: Django project test and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup docker compose
      run: docker compose up -d
    - name: run tests
      run: docker compose docker-compose-stage.yml exec backend sh -c "pytest ."

 deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Arvan Cloud
        env:
          HOST: ${{ secrets.ARVAN_HOST }}
          USER: ${{ secrets.ARVAN_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST "\
            cd ${{ secrets.DEPLOY_PATH }} && \
            git pull origin main && \
            docker-compose -f docker-compose-stage.yml pull && \
            docker-compose -f docker-compose-stage.yml up -d --build \
          "